"""empty message

Revision ID: a56b3c8ca4ca
Revises: 10b6dfca9c5a
Create Date: 2021-11-21 17:57:36.538140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56b3c8ca4ca'
down_revision = '10b6dfca9c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form__email', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('form__email', sa.Column('unsubscribed', sa.Boolean(), nullable=True))
    op.add_column('form__email', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form__email', 'verified')
    op.drop_column('form__email', 'unsubscribed')
    op.drop_column('form__email', 'token')
    # ### end Alembic commands ###
